// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyllddcawsacmroyffgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5bGxkZGNhd3NhY21yb3lmZmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODI0MTMsImV4cCI6MjA3Njc1ODQxM30.TRsFYD1cBnJWQTmjIIQGx0aRUQ1Tg-dwF8Rptx1oYiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});